services:
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
